services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: ${WORKDIR}
    volumes:
      - ./app:${WORKDIR}
    networks:
      - symfony
    depends_on:
      - db
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:${WORKDIR}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: postgres:16-alpine
    container_name: symfony_postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/db/pgdata:/var/lib/postgresql/data
    networks:
      - symfony

networks:
  symfony:
